Flz 4219 like model
folloze/client-sdk pull request #107
Opened 2023-04-19 06:38 UTC by danaturjeman-folloze

2023-04-19 06:38 UTC, TanyaFolloze commented
Task linked: [FLZ-4219 Infra - Like Model analytics internal refactor](https://app.clickup.com/t/3749831/FLZ-4219)

2023-04-20 07:55 UTC, rotemgrim requested changes

2023-04-20 07:55 UTC, rotemgrim commented on src/common/helpers/leadEventTracking.ts
>  export type TrackedLeadEvent = TrackedLeadLinkClick | TrackedLeadDownloadFile;
missing TrackedLeadLikeContent

2023-04-20 08:02 UTC, rotemgrim approved these changes

2023-04-20 08:03 UTC, merged