add Folloze.linkCtaClick event
folloze/client-sdk pull request #117
Opened 2023-05-18 13:50 UTC by TanyaFolloze

2023-05-18 13:50 UTC, TanyaFolloze commented
Task linked: [FLZ-6107 Implement client side events for "Folloze.linkCtaClick"](https://app.clickup.com/t/3749831/FLZ-6107)

2023-05-21 07:33 UTC, itamargolan requested changes

2023-05-21 07:33 UTC, itamargolan commented on dist/src/common/interfaces/IEvent.d.ts
> +export declare type PUBLIC_INCOMING_EVENT_ACTION = "Folloze.consentGiven" | "Folloze.stopTrackingForVisit" | "Folloze.linkCtaClick";
It should be under PUBLIC_OUTGOING_EVENT_ACTION

2023-05-21 07:33 UTC, itamargolan commented on src/common/interfaces/IEvent.ts
> +export type PUBLIC_INCOMING_EVENT_ACTION =
It should be under PUBLIC_OUTGOING_EVENT_ACTION

2023-05-22 07:46 UTC, itamargolan approved these changes

2023-05-28 09:43 UTC, rotemgrim approved these changes

2023-05-28 09:56 UTC, merged