Llm integration
folloze/client-sdk pull request #135
Opened 2023-10-31 16:26 UTC by TanyaFolloze

2023-10-31 16:45 UTC, TanyaFolloze commented
Task linked: [FLZ-7957 Generate text for single section](https://app.clickup.com/t/3749831/FLZ-7957)

2023-11-01 12:18 UTC, rotemgrim requested changes

2023-11-01 12:18 UTC, rotemgrim commented on src/common/interfaces/IEvent.ts
> +    | "generate-section-text";
change to something like "generate-ai-action" to include all other future events (with a switch case)

2023-11-01 12:18 UTC, rotemgrim commented on src/common/interfaces/IInitialState.ts
> +        genAi: boolean;
check that its always exists on the server

2023-11-02 08:37 UTC, TanyaFolloze commented
@rotemgrim some github voodo happened, i re-created the pr https://github.com/folloze/client-sdk/pull/136
i renamed the branch but github didnt update for some weird reason and it didnt get my pr changes
im closing this one

2023-11-02 08:37 UTC, closed without merging