Flz 7957 section text generation
folloze/client-sdk pull request #136
Opened 2023-11-02 08:36 UTC by TanyaFolloze

2023-11-02 08:36 UTC, TanyaFolloze commented
Task linked: [FLZ-7957 Generate text for single section](https://app.clickup.com/t/3749831/FLZ-7957)

2023-11-05 09:35 UTC, rotemgrim approved these changes

2023-11-13 10:04 UTC, rotemgrim requested changes

2023-11-13 13:49 UTC, rotemgrim approved these changes

2023-11-30 13:18 UTC, TanyaFolloze commented
will be merged with https://github.com/folloze/client-sdk/pull/142

2023-11-30 13:18 UTC, closed without merging