FLZ:8231: Upload video
folloze/client-sdk pull request #155
Opened 2024-01-02 14:08 UTC by adi-heffer-folloze

2024-01-02 14:08 UTC, TanyaFolloze commented
Task linked: [FLZ-8231 Events - Simulive - Upload video](https://app.clickup.com/t/3749831/FLZ-8231)

2024-01-03 12:49 UTC, rotemgrim requested changes

2024-01-03 12:49 UTC, rotemgrim commented on src/common/helpers/mediaHelpers.ts
split into 3 files (its too large)

2024-01-03 13:14 UTC, rotemgrim requested changes

2024-01-03 13:14 UTC, rotemgrim commented on src/common/helpers/mediaHelpers.ts
> +                            uploadBytesTrace[chunkIndex] = bytesLoaded;
try making this calculation with kind of throttling (no need to update the browser ui if there is no change in percentage)

2024-01-03 13:14 UTC, rotemgrim commented on src/common/helpers/mediaHelpers.ts
> +                            uploadBytesTrace[chunkIndex] = bytesLoaded;
make sure its not very complex (if it is just drop it)

2024-01-03 15:43 UTC, maor-folloze approved these changes

2024-01-28 13:00 UTC, rotemgrim approved these changes

2024-01-28 13:41 UTC, merged