Cloudinary video player
folloze/client-sdk pull request #30
Opened 2022-07-03 13:14 UTC by InbalMiller

2022-07-03 18:02 UTC, itamargolan requested changes

2022-07-03 18:02 UTC, itamargolan commented on src/common/helpers/mediaHelpers.ts
> +    public videoPlayerScriptUrl = "https://unpkg.com/cloudinary-video-player@1.9.0/dist/cld-video-player.min.js";
please take the light version

2022-07-04 06:58 UTC, InbalMiller commented on src/common/helpers/mediaHelpers.ts
> +    public videoPlayerScriptUrl = "https://unpkg.com/cloudinary-video-player@1.9.0/dist/cld-video-player.min.js";
updated

2022-07-04 08:13 UTC, itamargolan approved these changes

2022-07-04 08:13 UTC, merged